/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const VanButton: typeof import('vant/es')['Button']
  const VanIcon: typeof import('vant/es')['Icon']
  const showFailToast: typeof import('vant/es')['showFailToast']
  const showNotify: typeof import('vant/es')['showNotify']
  const showToast: typeof import('vant/es')['showToast']
}
