/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutmeTag: typeof import('./src/components/AboutmeTag.vue')['default']
    E5dateForm: typeof import('./src/components/E5dateForm.vue')['default']
    E5sharingProgress: typeof import('./src/components/E5sharingProgress.vue')['default']
    RelatedUsers: typeof import('./src/components/RelatedUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestBox: typeof import('./src/components/TestBox.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
    UserItem: typeof import('./src/components/UserItem.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCircle: typeof import('vant/es')['Circle']
    VanCol: typeof import('vant/es')['Col']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPickerGroup: typeof import('vant/es')['PickerGroup']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSlider: typeof import('vant/es')['Slider']
    VanStep: typeof import('vant/es')['Step']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSteps: typeof import('vant/es')['Steps']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
